language: node_js
node_js:
- '6'
- '5'
script:
- grunt
deploy:
  provider: npm
  email: mcp_infrastructure@cimpress.com
  api_key:
    secure: 'sVXaF3ZHyjkyalHEjEPIbb4KoL2yyrUNMd9lP/6d3dTxeRy2+MqdySdomeqDG3ILQ++0pDlNS0abHdMvANaa758tUX0k3BVRjZQ4IrijMLPF1b1DTF3dn81TfOUIFM377RZCAkXJ7urlydeFTVxeO6qAsmcAdYRdT8yWQ8Hj7y6dgehZcFUdypISf1qq+f0RBTFRI4FmLVQf2dzScubsVqF8trWNEBchnJQHR9CxmWmrXAl4nUmh7AR2r62qaz/LqoJzHpKWXheuLnzmIp1D6qnyw9o6Jksb1Y49nlEH0lDrt8CvmChH+zekn9s2QqZDgCp6ZhOz2ugsjUntAb5ALFbOJWyZm978KXHXy6ClcYr4N6pIJH91rH/nTkTrDrtRYVddAO8Yz5sakoQBldlPidUUpLKow4kCn3JQF6P7+i9iVeh+jUkVhGIvWZ8msKnCRUcsmrqSuEj8rkintm9TYqaB1m/tapuIrIm/LETL39UjFayHmDrwZGFB5QwohXN54D/yfLYHdYLpyY3u/kyPyEPE4YFl9mdvQZ3RK8ZfOAh+6+aD6oAPXhIgJz+CqPH9RftkCJCk+3KlMEU1s39ADNOhlx0kbmiB+PwJVpUIf0KaSfFwlsYTq09RW88MWJfuhOGXObzyaYFWBTMpkF2DduElFM+CJyEtgZrnPcayyNE='
  on:
    tags: true
    branch: master
    node: '5'
